### ISSUE TITLE
is it only support 32bit binary and ida 6.9?

### ISSUE THREAD

**Issue by sucof** [strongcourage/uafuzz#1]
Hi, Bardin and Nguyen, in your  instructions of installation, it need ida pro 6.9(32bit), does it mean that 64 bit programs are not supported? and ida pro7.0, 7.5 or other versions not supported?

**Comment by strongcourage** [comment]
Hi @sucof,
Yes, it currently supports only 32-bit binaries, but the approach is architecture independent. I used Ida 6.9, but if you can run the [IDA script](../tree/master/binsec/src/ida/ida.py) with newer versions, it should be ok as the final goal of IDA is to extract the call graph and CFGs for further analysis.
Best.

**Comment by sucof** [comment]
Thanks, strongcourage, if I want to fuzzing 64-bit binaries, what can I do? can you give me some advices?
Best!

**Comment by strongcourage** [comment]
I think you should mostly update the static part, for example generate call graph and CFGs of 64-bits binaries and preprocess the Valgrind's output. For the fuzzing part, you should compile the QEMU 64-bit. Overall it requires quite a lot of engineering effort.
Best.

**Comment by sucof** [comment]
Thanks.
