### ISSUE TITLE
can't generate .ida and .idb files by using the script

### ISSUE THREAD

**Issue by sh0ve1** [strongcourage/uafuzz#4]
Hi, guys
The version of my ida pro for linux is 6.4. When I execute it like this
![图片](https://user-images.githubusercontent.com/51234150/158122968-8d421f6f-b5b1-48a8-b0a6-246788235495.png)
I try to use the script generate .ida and .idb files.

I found the two code `ida_cmd = ida_path + " -B \"-S" + ida_script_path + " -o=" + out_dir + "\" " + tmp_file` and `parse_cmd = ida_path + " -A \"-S" + ida_script_path + " -o=" + out_dir + " -cg=True\" " + idb_file` can't generate .ida and .idb files. 

Besides，I don't understand its function of the code `binida_cmd = " -ida -isa x86 -quiet -ida-o-ida " + ida_file + " -ida-loglevel " + log_mode`. It doesn't seem to have done anything.

**Comment by sh0ve1** [comment]
maybe，I know the reason. The binsec requires ida pro 6.9

**Comment by strongcourage** [comment]
@sh0ve1 : We've used the IDA Pro version 6.9 for binary disassembling, so maybe your version (6.4 or 7.4) is not compatible to run the scripts. Technically, it could work with other x86 disassemblers, but we currently don't have time to update the tool.
Best.

**Comment by sh0ve1** [comment]
Dear @strongcourage ,
Thank you for your reply. I want to determine if a key code is missing on line 62 of preprocess.py, like `os.system("binida_cmd")`.  It execute run_ida.py to generate .ida  and .idb files. 
Best

**Comment by sh0ve1** [comment]
Dear @strongcourage ,
I have a puzzle about your paper name UAFUZZ, why do you want call instruction became the end of basic blocks instead of inside? Can you tell me your idea?

**Comment by strongcourage** [comment]
Hi @sh0ve1,
The current version supports generating .ida files or load & processing existing .ida files (only for evaluated bugs in case you don't have IDA Pro).
One basic block of IDA may have several call instructions, thus I need to split those kind of basic blocks into a sequence of blocks. It is useful for AFL-QEMU to keep track of edge coverage in runtime. In other words, I need to modify IDA's outputs to be compatible with AFL-QEMU.

**Comment by sh0ve1** [comment]
@strongcourage 

Thanks for your interpretation. 

When I generated .idb file by executing this command `ida.exe -B"-Sida.py -o=D:\Program Files\IDA_Pro_v7.5_Portable\ --call-graph=True --ida-graph=True" .\test`

![图片](https://user-images.githubusercontent.com/51234150/159199084-f0acc282-7909-4134-81e0-1a63d7b5f835.png)

Then I try to excute `ida.exe -A"-Sida.py -o=D:\Program Files\IDA_Pro_v7.5_Portable\ -cg=True" .\test.idb`. But it just opens ida gui and  creates some files temporarily instead of .ida file.
![图片](https://user-images.githubusercontent.com/51234150/159199516-216d6fd0-211d-43b2-ad90-21c32ca76c98.png)

My command is woring?

**Comment by strongcourage** [comment]
Hi @sh0ve1, 
The goal of running this script is to (1) generate `.idb` file which is the IDA database of the binary; (2) generate `.ida` file in the format we want. You can run this script on GUI, but in this case I run it using command lines for automation. Therefore, the expected outputs include both `.idb` and `.ida` files. 

In your case, please recheck output of the Python script (maybe it is not compatible with your IDA version, thus produces some errors). If everything works as expected, the GUI will automatically be closed, and all intermediates files will be removed.

**Comment by sh0ve1** [comment]
@strongcourage Thank you for the details.
